### ISSUE TITLE
code is too complex; needs to be simplified

### ISSUE THREAD

**Issue by emerald73** [shitty-esolang-stuff/bf-text-interpreter#1]
Dear Mr. "Sh-wayz",
    I am writing this issue to shed some light on the fact that after reviewing this code, I have determined that it is far too complex and confusing to the average programmer, and needs to be simplified. The absolutely massive codebase ",[.,]" I feel is far too long, and is a struggle to read through in one sitting, so I propose it be cleaned up and trim out any unnecessary parts to reduce the code size.
         
                                         Signed,
                                             emerald73

**Comment by Sh-wayz** [comment]
Salutations my good sir, 
    
While I recognise that you may have issues understanding the rather intimidating codebase, the average programmer is far more intelligent and handsome thant you are, and should have no problems with it at all. For proof, you need only to refer to your grades, and the nearest mirror. It is impossible to fix both your intellect and your face, and I kindly suggest you stop forthwith lest you drag other, normal programmers down to your level. Have a marvelous day, and good luck with the plastic surgery.

                                               - Regards,
                                                       Sh-wayz
